### ISSUE TITLE
Topic list for subscription and publication

### ISSUE THREAD

**Issue by Changliu52** [HJReachability/fastrack#1]
Hi,
Thank you for sharing this impressive code.
I am looking for a ros package, which takes the octomap and current pose as inputs and produces continuous trajectory points as output. 
I wonder if this package has similiar interface?

Kind Regards,
Chang

**Comment by dfridovi** [comment]
Hi Chang,

Thanks so much for reaching out. The short answer is yes, you can definitely use FaSTrack to do that, provided that you first wrap OctoMap so that it implements our [Environment](https://hjreachability.github.io/fastrack/doc/html/docs/classfastrack_1_1environment_1_1Environment.html) interface. If you do that, then things should be pretty much plug 'n play. If you get it to work please do create a pull request and I'll see if we can add it!

Hope this works for you, and feel free to follow up if you have further issues.

Best,
David

**Comment by Changliu52** [comment]
OK thank you for the info
